In [13]:
# Import OneHotEncoder for converting categorical data into numerical form
from sklearn.preprocessing import OneHotEncoder
# Import NumPy for handling arrays
import numpy as np
# Create an array of categorical data (LLM applications)
# reshape(-1, 1) converts it into a column format required by OneHotEncoder
data = np.array(["chatbots", "virtual assistants", "AI research", "chatbots"]).reshape(-1, 1)
# Create the OneHotEncoder object
# sparse_output=False returns the result as a normal NumPy array instead of a sparse matrix
encoder = OneHotEncoder(sparse_output=False)
# Fit the encoder to the data and transform the categories into one-hot vectors
one_hot = encoder.fit_transform(data)
# Print the one-hot encoded result
print(one_hot)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
